name: Run Tests

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-asdf-00
          path: ~/.asdf
      - uses: asdf-vm/actions/install@v4
        with:
          tool_versions: |
            bun 1.2.21
      - run: |
          asdf install deno 2.4.5
          asdf install bun 1.2.21
          asdf install nodejs 16.4.1
          asdf install nodejs 22.19.0
          asdf install nodejs 24.7.0
      - run: bun install
      - run: bun test
